developer-portal/content

CONTRIBUTING.md
I did a few formatting and grammar fixes, also added links where appropriate and reworded a few sentences.
=> Some minor fixes for CONTRIBUTING.md

tech/languages/php/pear-installation.md, tech/languages/php/php-installation.md, tech/languages/php/symfony-installation.md, tech/languages/php/zend-installation.md
I will appreciate your feedback and I hope I didn't make any serious mistakes :)
It's probably short, but enough to get PHP working and start developing with it.
=> Initial PHP Content

CONTRIBUTING.md
just a nitpick
https://github.com/golang/go/wiki/GOPATH
=> contributing: GOLANG -> GOPATH

start/hw/arduino/about.md
Signed-off-by: Tomas Hozza <thozza@redhat.com>
=> Added content for Arduino, Arduino IDE and Ino tool

tech/database/sqlite/about.md
Proposed content for SQLite entry.
Should resolve #15 .
=> Created basic content for SQLite

tech/database/mariadb/about.md
=> Add first content for MariaDB

tech/database/mariadb/about.md
Based on comments in issue #14.
=> Use only one top level heading

tech/languages/java/about.md, tech/languages/java/java-build-tools-installation.md, tech/languages/java/java-installation.md, tech/languages/java/java-sig.md
Initial "something" for Java. It's marked as work-in-progress for now, because I would like to have it reviewed by other Java SIG members first.
=> Initial content for Java

tools/docker/compose.md
It's still not done, there are still some things I want to improve:
=> add docker-compose content

tech/languages/c/automake.md, tech/languages/c/c-devassistant.md, tech/languages/c/c_installation.md, tech/languages/c/cmake.md, tech/languages/c/cpp_installation.md, tech/languages/java/java-devassistant.md, tech/languages/nodejs/about.md, tech/languages/nodejs/nodejs-devassistant.md, tech/languages/perl/perl-devassistant.md, tech/languages/php/pear-installation.md, tech/languages/php/php-devassistant.md, tech/languages/php/symfony-installation.md, tech/languages/php/zend-installation.md, tech/languages/python/python-devassistant.md, tech/languages/ruby/ruby-devassistant.md
Signed-off-by: Petr Hracek <phracek@redhat.com>
I have found several missing order tags.
=> Ordering fixes and using DevAssistant parts

tools/devassistant/about.md, tools/devassistant/developers.md, tools/devassistant/notes.md, tools/devassistant/tutorials.md
Please go through the links and change the ones starting with `#` (local ones) so that they point to proper pages/headings. Thanks.
=> Content for DevAssistant

tech/languages/go/go-installation.md
@shaded-enmity @ingvagabund PTAL
=> go: use $HOME/work as a Go workspace

tech/languages/groovy/groovy-installation.md
Add few words about Groovy in Fedora.
=> Initial content for Groovy

tools/docker/compose.md
Follow-up on #59 
@strzibny Thanks a lot for your very thorough review.
=> improve docker-compose content

tools/docker/docker-images.md
Providing some more information, giving more details and complete list of images.
=> Extend the basic info

tools/vagrant/about.md
Signed-off-by: Richard Marko <rmarko@fedoraproject.org>
=> vagrant: fix work/works typo

tech/languages/haskell/cabal.md, tech/languages/haskell/haskell-installation.md, tech/languages/haskell/sig.md
Signed-off-by: Ricky Elrod <ricky@elrod.me>
=> Add Haskell

tech/database/postgresql/about.md
Yum has been deprecated in Fedora. dnf is the new package manager
=> Replace yum with dnf

tools/docker/compose.md
b/c it looks like that parser makes it and inline codeblock
https://developer.fedoraproject.org/tools/docker/compose.html#create-django-project
Don't know how to verify
=> docker compose: add newline before codeblock

tech/languages/c/c-devassistant.md, tech/languages/c/c_installation.md, tech/languages/c/cpp_installation.md, tech/languages/java/java-devassistant.md, tech/languages/nodejs/nodejs-devassistant.md, tech/languages/perl/perl-devassistant.md, tech/languages/php/php-devassistant.md, tech/languages/python/django-installation.md, tech/languages/python/pypi-installation.md, tech/languages/python/python-devassistant.md, tech/languages/python/python-installation.md, tech/languages/ruby/ruby-devassistant.md, tools/docker/docker-usage.md, tools/vagrant/vagrant-docker.md, tools/vagrant/vagrant-libvirt.md, tools/vagrant/vagrant-virtualbox.md
Usually typos and small rewordings.
=> Various fixes

tech/languages/python/sphinx.md
This PR adds content of #97 
Can we please discuss whether you consider it useful, and what should be improved?
Also, I would like to add image there, to let users see, what result they can expect. Please see #99.
=> Add sphinx artictle

tools/virt-builder/about.md
`virt-builder`[1] is a tool that allows you to quickly build (and
customize) virtual machine disk images.
[1] http://libguestfs.org/virt-builder.1.html
=> tools: Add virt-builder

README.md, tools/abrt/about.md
=> abrt: initial

start/sw/web-app/django.md
=> Python Django

deployment/rpm/about.md
The example spec doesn't work as-is. For a quick start, it doesn't exactly make a buildable RPM.
This takes the complete example from the tutorial page and puts it in here, so that developers can see a complete, buildable, and usable RPM.
=> Fill in the example RPM spec

tech/languages/python/pygobject.md
Although this article is in the tech/languages/python section, it will be referenced also in the upcoming Desktop GUI Application (gui-app) section.
=> Introduce pygobject article

tech/languages/c/gtk.md
Although this article is in the tech/languages/c section, it will be referenced also in the upcoming Desktop GUI Application (gui-app) section.
I took the liberty to be more abstract in the C article, considering the C programmers would be a little bit more advanced the the average.
=> Introduce gtk article

tools/virt-builder/about.md
Made a minor change to the snippet for Virt-builder
=> Fixed spelling error

start/sw/web-app/jekyll.md
Hi,
I wrote some short article about [Jekyll](https://jekyllrb.com/) static site generator.
=> Add web-app/Jekyll article

tech/languages/ruby/ror-installation.md
NodeJS should work just fine as a replacement
=> rubygem-therubyracer was retired from fedora

tools/eclipse/about.md
List Eclipse in the tools page.
=> Add Eclipse page in the tools.

tech/languages/python/flask-installation.md
I've added some little improvements to [python/flask]. Namely, it is example application (minimal application from flask docs) and description how to run it.
=> [python/flask] Provide example application and describe how to run it

start/sw/web-app/rails.md
The proper way to install ruby and rails with rbenv
=> How to install ruby and rails with rbenv

tech/languages/c/cmake.md
Added text recommending out of band builds
=> Update cmake.md to recommend out of source builds

tech/languages/rust/format-rust-code.md, tech/languages/rust/rust-cargo.md, tech/languages/rust/rust-installation.md, tech/languages/rust/rustfmt.md
Related to issue #151 
**State**: WIP, Rust is not yet in Fedora.
=> Rust language proposal

deployment/maintain/about.md
=> Fix a ction to section

tech/languages/python/multiple-pythons.md
I'd also suggest to move this up a bit in the menu, but I didn't make that change so it's easier to merge in
the future without conflicts. Reordering can be done later.
=> Multiple Python interpreters

tech/languages/python/scipy.md
Preview available here:
https://github.com/rpavelka/content/blob/52cbc72d562cddd872082b1df81de7286f1c01c3/tech/languages/python/scipy.md
=> Add article on Python Scientific Stack

tech/languages/python/django-installation.md, tech/languages/python/flask-installation.md, tech/languages/python/pypi-installation.md, tech/languages/python/python-installation.md
Hi,
I've improved Python tutorials:
- Add info about virtual environments.
- Show how easy is to use Python stuff.
- Delete obsolete things like bpython.
- Use just Python 3.
=> Modernize python tutorials and add info about venv.

deployment/openshift/about.md, tools/docker/docker-installation.md
=> Contribute content about OpenShift v3

tech/database/mongodb/about.md
How install a specific version of MongoDB or install the last available in official repository
=> How install MongoDB

tech/languages/java/java-build-tools-installation.md
This should help new java developers get started with maven, and
start to better understand the maven build livecyles, and how to
structure / define a maven project.
=> Providing Details for how to get started with a Maven Project.

tools/docker/about.md, tools/docker/docker-configuration.md, tools/docker/docker-images.md, tools/docker/docker-installation.md, tools/docker/docker-usage.md
Updated with docker links in `tools/docker` directory.
=> Fixed docker links with updated ones

tech/database/mongodb/about.md
Need space after # for Markdown to parse properly
=> Space after # in title

start/sw/mobile-app/mobile-installation.md
- Remove old link
- Add basic android studio setup instructions
=> Update android setup

tech/languages/csharp/mono-installation.md
related to developer-portal#217
=> fixing the titles and subtitles of the Mono page

tech/languages/csharp/mono-installation.md
=> updating the documentation section and API section for Mono

tech/languages/csharp/csharp-ide.md
This is relevant change to the website PR [website/pull/60](https://github.com/developer-portal/website/pull/60)
=> *csharp: Added table style properties

tools/virt-builder/about.md
- Remove examples of old Fedora releases
- Describe a bit about "--os-variant"
- Some minor wording tweaks
Signed-off-by: Kashyap Chamarthy <kchamart@redhat.com>
=> Update `virt-builder` subsection

start/sw/web-app/django.md
corrected the commands for installing virtualenvwrapper in python 2 and 3 and some formatting
=> Fix Django page in `Web Application` subsection

deployment/openshift/about.md
Fixed
[Online Developer Preview](https://www.openshift.com/devpreview/index.html)
=> Fixes #184 - Unclickable Openshift Link

tech/languages/python/multiple-pythons.md
See https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/thread/VTOQDUSGTMGOZOJHK4Y6GNVVLHA36QEC/
=> Remove Python 3.3

deployment/copr/copr-cli.md
Fedora release is variable, only change version in _config.yml.
=> Use `fedora_release` variable

start/hw/arduino/about.md
Ino is no longer available in the repository.
=> Ino not available

tech/languages/csharp/dotnet-installation.md
Hi, I'm not sure whether it's okay to word it the way it is with x.y version. Is this okay?
=> *csharp: Updated .NET Core versions

tech/languages/java/java-installation.md
Should be good until 2020 when JDK 15 releases.
=> Updated version to Java 11, the latest LTS release

start/sw/web-app/laravel5.md
A more modern, and a more Fedora way to install Laravel, and Nginx is now more preferred for its performance.
=> Update Laravel 5 Doc for better Development

tech/languages/dotnet/about.md, tech/languages/dotnet/dotnetcore.md
=> Fix .NET Core page title

tech/database/sqlite/about.md
Removed the unmaintained 6 years old Sqliteman and replaced with Sqlitebrowser
=>  Removed unmaintained sqliteman

start/sw/web-app/laravel5.md
Apache needs the php package to work correctly.
=> Add instructions for Apache

tech/database/mongodb/about.md
project really dead and buggy. may be someone know better monogo-gui, and may be we must delete mongotron section at all
=> Mongotron warning

tech/database/postgresql/about.md
=> Update about.md of PostgreSQL

tech/languages/rust/format-rust-code.md, tech/languages/rust/further-reading.md, tech/languages/rust/rust-cargo.md, tech/languages/rust/rust-installation.md
- Updated instructions for installing `rustfmt`.
- Updated the Rust Book link.
- Added a link to the Cargo Book.
- Fixed minor typos.
=> Updates for tech/languages/rust/

tech/languages/dotnet/about.md, tech/languages/dotnet/dotnet-ide.md, tech/languages/dotnet/dotnet-sig.md, tech/languages/dotnet/dotnetcore.md, tech/languages/dotnet/mono.md
=> Update dotnet pages to reflect that it's now packaged in f32

tech/languages/java/java-build-tools-installation.md
See, e.g., https://bugzilla.redhat.com/show_bug.cgi?id=1824088#c1
=> Gradle was retired from Fedora

tech/languages/c/cpp_installation.md
There is sudo before the commands which need root access anyway (the dnf commands) and it's good practice to always use the least amount of required privilege.
=> canged # to $

start/sw/web-app/about.md
The text is only meant to give a short introduction for anybody new for web development, and also to link to other pages in the section.
=> Add content to start/sw/web-app/about.md

tech/languages/java/java-installation.md
Replace openjdk15 instead of openjdk11 in the text
=> Replace openjdk15 on java-installation.md

tech/languages/ocaml/ocaml-installation.md
I wrote the Markdown instructions to install the OCaml language and OPAM manager, but I just wont figured out how to add the language logo to the repo yet. I hope to contribute with more sections in this page on the future.
=>  Add guide for the OCaml language

tech/languages/fortran/fortran-installation.md
Getting started with Fortran in Fedora.
=> Add content for Fortran language

tech/languages/lua/lua_installation.md
I am going to write series of article about Lua, this is the first one.
=> Added first Lua article.

tech/languages/python/pipenv.md
Hi,
There was a typo and this is a fix.
Thanks.
=> Fix typo on pipenv page

tech/languages/ruby/ruby-installation.md
=> Change long versions of no-doc for the short one

tech/languages/swift/swift_installation.md
Hello-
I added Swift under the language section. It follows other languages in style so hopefully there aren't any issues. I'm not sure how to add a logo though.
=> Initial commit of Swift in the language section

start/hw/arduino/about.md
Resolves: https://github.com/developer-portal/content/issues/436
=> Add flatpak remote-add step to arduino-ide installation.

tech/languages/dotnet/dotnet-ide.md
Describe the RPM installation in more detail.
=> Describe VSCode RPM installation steps.

tech/languages/gjs/gjs-installation.md
We had a whole page hidden :) I have also added a logo PR to website https://github.com/developer-portal/website/pull/135
=> Fix Gjs's yaml format to actually show up on the page.

start/hw/arduino/about.md
I'd rather not use the comment style, looks very strange, as if quoting something. Simple is better IMO.
=> arduino about page: style change

start/sw/web-app/about.md
In line 14, changed "nad" to "and".
=> Minor spelling correction

tech/languages/ruby/gems-installation.md, tech/languages/ruby/ruby-installation.md
=> Update ruby pages.

tech/database/mongodb/about.md
- updated instruction to current version
`mongodb-org-4.4` => `mongodb-org-6.0`
=> UPDATED instruction

tech/database/sqlite/about.md
Fixes https://github.com/developer-portal/content/issues/475
=> Remove sqlite-jdbc mentions, it was removed from Fedora.

start/sw/web-app/about.md
fixes: https://github.com/developer-portal/content/issues/476
=> Remove Atom from web-app about.md, the IDE was sunset.

tech/languages/python/sphinx.md
I've applied many of the suggestions made by @pvalena in order to improve the latexpdf section.
=> Improving the latexpdf section on sphinx.md

tools/vagrant/vagrant-nfs.md
Fixes: https://github.com/developer-portal/content/issues/495
=> Fix the content for /etc/sudoers for passwordless nfsd setup in vagrant.

tech/languages/rust/further-reading.md
Fixes: https://github.com/developer-portal/content/issues/465
=> Introduce sections for rustup in Further reading section of Rust.

start/sw/web-app/rails.md
Fixes: https://github.com/developer-portal/content/issues/494
=> Revitalize web-app section about Rails.

start/sw/web-app/rails.md
=> Mention nodenv for installing nodejs

deployment/copr/copr-cli.md
The direct link to the playlist is here:
https://www.youtube.com/playlist?list=PLEOLABfRmCVjhTCrxiHNE9KwDepnbhIXa
Or we can point to the documentation instead:
https://docs.pagure.org/copr.copr/video_tutorial.html#video-tutorial
=> Mention copr-cli video tutorial

tools/docker/docker-installation.md
Updated a command. 
The previous one returns the following error:
> Unknown argument "--add-repo" for command "config-manager". Add "--help" for more information about the arguments.
Tested on Fedora 41.
=> Updated a command in docker-installation.md
