developer-portal/content

tech/languages/java/java-devassistant.md
"create a Maven build manager" sounds a bit strange.
=> Improve wording in Java/DevAssistant section

tech/languages/nodejs/modules.md
There's no need to use sudo to link a module to the working directory, and it probably isn't a good idea.
=> Drop redundant sudo

tools/vagrant/vagrant-libvirt.md
It is confusing to have word 'group' mentioned twice on single page, each time in completely different context. This is attempt to clarify this.
BTW not sure if this terminology is used on other pages, but it should be clarified/keep consistent there as well.
=> Distinguish between package collection and user group

tech/languages/c/c_installation.md
Installing libgcc.i686 is not intuitive for people not familiar with Fedora packaging.
=> Section about 32-bit compilation added to c_installation.md

tech/database/mariadb/about.md
The text in second part of the page is formatted wrong, because of missing empty lines (at least I suppose):
https://developer.fedoraproject.org/tech/database/mariadb/about.html
=> Not properly formated text after generation

deployment/rpm/about.md
The make statement is supposed to be `make %{?_smp_mflags}` since it's potentially not always defined.
See complete hello.spec here: https://fedoraproject.org/wiki/How_to_create_a_GNU_Hello_RPM_package#A_complete_hello.spec_file
=> Add missing condition check

tech/languages/php/php-sig.md
Since we have a section for PHP, we should reference the Fedora PHP SIG.
=> Add item about PHP SIG

deployment/secondary_architectures/about.md, deployment/secondary_architectures/powerpc.md, deployment/secondary_architectures/s390.md
This commit adds a new sub-section "Secondary Architectures" under "Deploy and distribute". It will help developers to build application for architectures s390(x), PowerPC using Fedora secondary koji.
=> Add content to build application for Secondary Architetcures

tech/languages/gjs/gjs-installation.md
Gjs is the GNOME Javascript binding. It will be referenced also in the upcoming Desktop GUI Application (gui-app) section.
In the metadata of this entry I implied the existence of a Javascript section. I propose it as a better way to organize the whole pletora of Javascript bindings, libraries, and frameworks (nodejs, AngularJS, Ember, gjs, ...)
=> Introduce Gjs article

deployment/maintain/about.md, deployment/maintain/rebase-helper.md, deployment/maintain/static-analysis.md
Signed-off-by: Petr Hracek <phracek@redhat.com>
This section introduce several tools which can be used for maintaining packages and detecting errors.
Nowadays it contains only rebase-helper and static analyses.
=> Introduce Maintain and Improve section

deployment/rpm/about.md
Fix typo in wiki page link "How to create and RPM package".
s/and/an/
=> Fix typo in wiki page link

tech/languages/csharp/mono-build-tools-installation.md
with the recent EOL of Fedora 22, there is no need for explanation anymore how to install nunit on Fedora 22 where it had a different package name.
=> updated installation instructions for nunit

deployment/copr/copr-cli.md
The old url was not the correct one, if one would try to login to get his API key, he would be redirected to the homepage of the new site. In fact I have the impression that the entire URL should be using a HTTP redirect to the new domain.
=> Fixed copr API URL

start/sw/mobile-app/mobile-devassistant.md
* `my_test` typo for consistency
* I wasn't sure at first about the `--name <your_project_name>` param,
but it's mandatory for the command. I didn't need to create a project,
I only wanted Android Studio for some existing projects, but it can definitely be deleted after.
* I added official instructions as we sometimes fall on devassistant
before the actual original documentation
* I added troubleshooting part concerning missing JDK Setup
=> Improved android-studio setup documentation :v:

tech/languages/ruby/ror-installation.md
Not `libxml2-devel` but `zlib-devel` is required for latest version Rails 5.0.0.1
```
$ gem install rails
...
Fetching: nokogiri-1.6.8.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing rails:
ERROR: Failed to build gem native extension.
current directory: /builddir/.gem/ruby/gems/nokogiri-1.6.8.1/ext/nokogiri
/usr/bin/ruby -r ./siteconf20161116-16260-y0m2cd.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.1.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
...
```
=> Update "Installing Rails from RubyGems.org" for Rails 5.0.x

start/sw/web-app/laravel5.md
Issue: http://stackoverflow.com/a/27915343/3060426
=> fix laravel command not found

tech/languages/python/django-installation.md, tech/languages/python/flask-installation.md, tech/languages/python/pypi-installation.md, tech/languages/python/python-installation.md
As of Python 3.6, pyvenv is deprecated in favor of python3 -m venv (see https://docs.python.org/3/library/venv.html#module-venv).
=> venv creation syntax update

tech/languages/python/scipy.md
* nose has nothing to do with science
* nose is dead, it says the following on the website:
> Nose has been in maintenance mode for the past several years
> and will likely cease without a new person/team to take over
> maintainership. New projects should consider using Nose2,
> py.test, or just plain unittest/unittest2.
=> Remove nose from Scientific Python

tech/languages/go/go-programs.md
The correct path is `$HOME/go/src/hello`, not `$HOME/go/hello`.
=> Correct path for Go hello example

tech/languages/haskell/leksah.md
`cabal` should be `cabal-install`
=> Fix wrong package name

tools/docker/docker-configuration.md
Hi
In _/etc/sysconfig/docker_ (which is the old conf location)
on line 9 there is written:
_Do not add registries in this file anymore. Use /etc/containers/registries.conf_
=> Change docker registries conf location

start/sw/web-app/php-symfony.md, start/sw/web-app/php-zend.md, tech/languages/php/php-frameworks.md, tech/languages/php/php-sig.md
First part of #237 
I will work on the second part (creating a web servers subsection) next week.
=> Moved all php web frameworks to web app

tech/languages/python/multiple-pythons.md
* Python 3.7 is coming to Fedora 26+
* Fedora < 25 is not supported
* python3-virtualenv now has the virtualenv-3 command
Please review. Do not merge before both of the following happens:
=> Update `Multiple Pythons` page

deployment/openshift/about.md
On Fedora 27, one should configure the Docker registries in `/etc/containers/registries.conf` instead of `/etc/sysconfig/docker`.
=> Update OpenShift's insecure registry instructions

tools/devassistant/about.md
Only link from 'tools/devassistant/about.md' was deleted.
=> Delete link: notes

tech/database/mariadb/about.md
Update to reflect current situation with MariaDB 10.2 and MySQL 8, mariadb-connector-c, mariadb-connector-odbc and mariadb-java-client.
Links updated
=> Update info for MariaDB 10.2 and Fedora 27/28

deployment/maintain/rebase-helper-integration.md, deployment/maintain/rebase-helper.md, deployment/maintain/static-analysis.md
Did some cleanup, lots of formatting, and some minor copyediting in `rebase-helper.md` in the wiki:
* Indented code blocks that are placed under bullet headings
* Fenced code blocks with ` ```sh ` and ` ```python3 ` to enable (minimal) syntax highlighting
* Fenced more filenames / shell commands / package identifiers with backticks
* Removed backtick fencing from some headings and other non-code-literal words in favor of bolding or other (non-monospaced) decoration.
* Some minor grammatical cleanup (on the section headings, primarily).
=> Update rebase-helper docs

tech/languages/python/multiple-pythons.md
Updated to support both F27/28 and F29/30
Once 28 is EOL, we can chnage the command to `dnf install virtualenv`
See https://src.fedoraproject.org/rpms/python-virtualenv/pull-request/5
=> There will no more virtualenv-X

tech/languages/csharp/dotnet-installation.md
Update installation instructions to the latest version.
Add link to sample console app.
=> Small updates in .net installation page

tech/languages/python/multiple-pythons.md
Fixes https://github.com/developer-portal/content/issues/283
This is only relevant for Fedora 29+, but it is written in a way that it can be merged even now.
=> Add a note about tox 3 not supporting Python 2.6

tools/vagrant/vagrant-libvirt.md
These are minor edits to the Vagrant libvirt page. I added a note about the performance hits (because this happened to me on my Fedora 28 workstation) and I also updated a project's GitHub URL since the upstream moved.
=> Add note about vagrant-libvirt qemu performance, update upstream URL

tech/languages/nodejs/nodejs.md
[Fedora Modularity](https://docs.fedoraproject.org/en-US/modularity/using-modules/) introduces multiple versions of packages in Fedora — and nodejs already has multiple versions available. This PR mentions them on the nodejs page.
=> Mention alternative versions of nodejs as modules

tech/languages/c/gtk.md
I just updated the command for the necessary installation. `webkitgtk3-devel` was retired and replaced with `webkit2gtk3-devel`. I just updated the command with that. Also, it is listed under gtk-3.0, so I mentioned that.
=> Updated gtk.md

deployment/secondary_architectures/s390.md
Putting `--scratch` before `build` results in the error `koji: error: no such option: --scratch`; putting it _after_ `build` works.
=> Updated position of --scratch

tools/vagrant/vagrant-nfs.md
`nfs ` service means NFSv4 in firewalld. `nfs3` is for NFSv3. I don't know in which version of Fedora the nfs3 firewalld service has been introduced. But it was there since at least F29.
NFSv3 is used by vagrant as default at this moment (https://www.vagrantup.com/docs/synced-folders/nfs.html):
> nfs_version (string | integer) - The NFS protocol version to use when mounting the folder on the guest. This defaults to 3.
=> Enable nfs3 service in firewall

deployment/flatpak/flatpak-usage.md
We now have Flatpaks built in the Fedora infrastructure, from RPMs. It would be nice to point users to it as an option alongside Flathub.
See https://blog.fishsoup.net/2018/12/04/flatpaks-in-fedora-now-live/
and https://docs.fedoraproject.org/en-US/flatpak/tutorial/
=> Add instructions to install Fedora Flatpaks

tech/languages/dotnet/dotnetcore.md
The getting started link to the official guide is using an old link that results in a 404. I have updated it to the new location.
=> Updating the link to the official guide for .NET Core.

tech/languages/python/django-installation.md, tech/languages/python/flask-installation.md, tech/languages/python/micropython.md, tech/languages/python/multiple-pythons.md, tech/languages/python/pygobject.md, tech/languages/python/pypi-installation.md, tech/languages/python/python-installation.md, tech/languages/python/python-sig.md, tech/languages/python/scipy.md, tech/languages/python/sphinx.md
Here's a big update to Python sections to keep them current.
The content was already reviewed by Python SIG members Zbyszek and Miro in https://github.com/encukou/content/pull/1
---
Update the list of Python versions.
Remove sections for recently removed interpreters.
Change the section order to put Multiple Pythons near the top,
since this is one of the main selling points of Fedora wrt. Python.
Warn that pip installs third-party software.
Explain more clearly why virtual environments are preferred over
Fedora packages for development.
Only keep the name "virtualenv" for environments created by the actual
`virtualenv` tool; otherwise switch "virtual environment" or just "environment".
Update Flask docs to reflect best practice there.
Add ESP32 to the MicroPython docs.
And further …
=> Update the Python docs

tools/vagrant/vagrant-nfs.md
as `newgrp` actually changes users group to that of the argument.
=> Use `sudo -u` instead of `newgrp`

tools/docker/compose.md
Found while fooling around on Fedora 33
=> There is no  `python`, only `python3`

tech/languages/nodejs/nodejs.md
npm will throw an error out of the box when installing global modules like _nodemon_ etc.
I've added a solution how to set the new npm global module directory.
=> Set npm global modules path

tools/docker/docker-installation.md
Docker fully supports cgroup v2 with Docker version 20.10.
=> docker: Drop information about switching back to cgroup v1

tech/languages/python/python-installation.md
- Fully switch to Python 3
- Mark instructions for opening the Terminal as specific to GNOME
=> Update Python guide

tech/languages/python/multiple-pythons.md
Related to https://github.com/developer-portal/content/issues/372
I've decided to keep the Jython info for the Fedora 34 release.
=> Mark Jython and Python 3.5 to be removed in Fedora 35

tech/languages/python/pypi-installation.md
- Add pip installation. The Python 3.10 package will no longer recommend `pip`, so the tool might not always be installed system-wide. (It will still be added to new virtualenvs, however.)
- Add a section on updating packages.
=> Update instructions for pip install

tools/vagrant/vagrant-nfs.md
- the libvirt provider interface virbr0 is using the `libvirt` firewall zone
https://libvirt.org/firewall.html#fw-firewalld-and-virtual-network-driver
=> Use libvirt firewall zone for nfs in vagrant

deployment/rpm/about.md
As of October 2016, https://fedoraproject.org/wiki/Mock says it is not maintained and directs users to https://github.com/rpm-software-management/mock/wiki instead.
=> Fixed bad link

tech/database/postgresql/about.md
When running the old command, it gives the output:
```
WARNING: using obsoleted argument syntax, try --help
WARNING: arguments transformed to: postgresql-setup --initdb --unit postgresql
```
This PR updates to the new argument syntax
=> Update `postgresql-setup` command

tools/vagrant/vagrant-libvirt.md
In Fedora, QEMU / Session is used. This is not documented properly. Advice users on what it is and how to revert in case it doesn't work for them.
=> vagrant-libvirt.md: QEMU / Session changes

tech/languages/python/fastapi-installation.md
Specifically, mention that Fedora does contain a `python3-fastapi` package.
Fixes #424.
=> Align virtualenv advice for FastAPI with Django/Flask

tools/eclipse/about.md
Eclise was retired in Fedora 35, the current way to install eclipse
is through flatpak.
Resolves: https://github.com/developer-portal/content/issues/413
Resolves: https://github.com/developer-portal/content/issues/428
=> Replace DNF with Flatpak installation for the eclipse IDE.

tech/languages/dotnet/dotnet-ide.md
Eclipse was retired in Fedora 35, therefore it is not installable through
DNF.
Resolves: https://github.com/developer-portal/content/issues/407
Fix link in dotNet to flatpak pages.
Resolves: https://github.com/developer-portal/content/issues/427
Tested locally. I was able to install and run a smoke test of the aCute extension.
=> Replace dnf install with flatpak install for Eclipse dotNet IDE.

tech/languages/java/java-build-tools-installation.md, tech/languages/java/java-installation.md
Update Java sections
- OpenJDK 15 is no longer available, use geniric, unversioned virtual package names.
- IcedTea-Web is retired.
- Use https links instead of http.
- Some git branches were renamed from master to main.
=> Update Java sections

tech/languages/ruby/ruby-installation.md
Ruby's irb apparently used to be provided by the ruby package, but is now provided by rubygems-irb.
=> Correct the package irb comes from

tech/languages/python/fastapi-installation.md
This reverts commit 63046c1e90f0f787eed5bace3ff0f1df440c3645.
The python-fastapi package has been retired due to lack of upstream support for Python 3.11.
=> Revert "Align virtualenv advice for FastAPI with Django/Flask (#425)"

tools/vagrant/vagrant-libvirt.md
instructions, and also fixed upstream docs link.
=> Update vagrant-libvirt page: qemu session

tech/database/mongodb/about.md
This is mostly based on the suggestions and content from this PR: https://github.com/developer-portal/content/pull/321
It is the last content update to attempt to bring a more current, at least partially working approach (99% working last I checked, but I do not have any realworld use case, so I cannot test the full extent), and with some fixups to better adhere to the Fedora Developer Portal content guide.
This will be accompanied by an email to fedora-devel calling for contributors once I collect all the components that suffer from similarly out-of-date content.
@pvalena PTAL,  IIRC, these steps have worked for 4.4 since I tested it around a month ago.
=> MongoDB deprecation

tech/database/cassandra/about.md
Cassandra is not available on Fedora and
the page wasn't updated in a long time and contains quite an outdated content.
=> Deprecate Cassandra page due to lack of maintanance.

tech/languages/groovy/groovy-installation.md
Groovy is not available in Fedora since October 2019
Resolves: https://github.com/developer-portal/content/issues/421
=> Deprecate groovy-installation.md.

tech/languages/rust/further-reading.md
RLS has been archieved and rust-analyzer is now officially recomended language server for rust
=> Replace RLS with rust-analyzer as prefered language server for rust

tech/languages/dotnet/about.md, tech/languages/dotnet/dotnetcore.md
.NET Core has reached its End of Life. Upstream also did a rename from .NET Core to .NET for the 5.0 release. The only supported versions of .NET are now 6.0 and 7.0.
=> Update .NET docs for .NET 7 release

tech/languages/c/gtk.md
The `gstreamer1-devel-docs` package is unavailable in Fedora due to missing dependency.
Additionally, put code formatting where appropriate.
Fixes: #463
=> Gtk docs package install step

tech/languages/ocaml/dune.md
I would like to propose the addition of a tutorial on Dune, the OCaml build system, to the Fedora Developer Portal.
Dune is a fast and flexible build system for OCaml that has gained popularity among OCaml developers. It provides a uniform interface for building, testing, and installing OCaml projects, and helps manage dependencies between packages.
Adding a tutorial on Dune to the Fedora Developer Portal would be highly beneficial for OCaml developers who are new to the language and want to get started with building projects. The tutorial would provide a step-by-step guide on how to install Dune, start a new project, build the project, and run it, as well as how to add a library to a Dune project.
Inclusion of this tutorial would make the Fedora Developer Portal a more comprehensive …
=> Add Dune section in OCaml content

tech/languages/go/go-installation.md
This PR adds notes on Fedora specific changes to the standard Go language installation.
=> Add Fedora Specifc Notes For Golang Page

start/sw/web-app/rails.md
This updates the document to use the packaged rbenv instead of installing it from git. It also updates the version numbers to be more recent.
epel-release installation is dropped since that only applies to Enterprise Linux. Even there EL8+ has nodejs packaged.
=> Update rails.md to use packaged rbenv

tech/languages/haskell/haskell-installation.md
The haskell platform package, while not seemingly available upstream is still in Fedora with the same spirit of providing full environment. According to waybackmachine for the page of 2021, the page only provided the `dnf install haskell-platform`.
That package is still well maintained, so let's point there for now.
Fixes: https://github.com/developer-portal/content/issues/493
=> Haskell platform page was deprecated upstream, Fedora still provides it.

tech/languages/dotnet/about.md, tech/languages/dotnet/dotnetcore.md
Announcements and external references:
- https://lists.fedoraproject.org/archives/list/dotnet-sig@lists.fedoraproject.org/thread/WRSA4NT74RUI3UZJENHJMH5S7WCZW6DP/
- https://devblogs.microsoft.com/dotnet/dotnet-7-end-of-support/
- https://github.com/dotnet/core/blob/main/releases.md#end-of-life-net-versions
=> Update .NET docs for .NET 7 EOL

tech/languages/rust/rust-cargo.md
Rust crates as packaged by Fedora are not really a suitable development target - this is one of the reasons why using them as a replacement for crates.io is not a supported use case.
While it was intentional that there was no documentation for how to use the Fedora packages for Rust crates for local development (it is not a supported use case, after all), this has caused confusion on multiple occasions. To remove this ambiguity, this commit explicitly documents this use case as unsupported in the developer documentation.
=> [Rust] Expand section about cargo + crate dependencies

tech/languages/dotnet/about.md, tech/languages/dotnet/dotnetcore.md
Removes .NET 6 and adds .NET 9. Fixes #549.
=> Update .NET docs, replacing .NET 6 with .NET 9

tech/languages/python/fastapi-installation.md, tech/languages/python/multiple-pythons.md
I happened to glance at the Python documentation and noticed it was outdated.
I've tried to fix those things which I have noticed, specifically:
- The list of available Python versions
- The old deprecation notice for fastapi; it is still packaged in Fedora
=> Update Python versions and remove old notice

deployment/flatpak/flatpak-usage.md
This PR is a quick fix for a currently broken link on the [Flatpak Usage page](https://developer.fedoraproject.org/deployment/flatpak/flatpak-usage.html), for "Flathub Applications."
- Original URL (404s): https://flathub.org/apps.html
- New URL: https://flathub.org/
Looks like the app search is now built into the homepage on Flathub. 
A similar URL, `https://flathub.org/apps/`, will also redirect to `https://flathub.org/`, hence my decision to use that URL.
=> Fixes Flathub app link 404 error

tech/languages/go/go-installation.md
Document changes to Go related environment variables for Fedora packagers and developers using Go.
=> Add Go 1.25 information

tech/languages/dotnet/dotnet-ide.md
monodevelop upstream has been discontinued, and monodevelop has been retired from Fedora 43
=> remove monodevelop
